package autoload

import (
	"bytes"
	"crypto/md5"
	"encoding/hex"
	"fmt"
	"strings"
	"text/template"
)

// renderData carries every value referenced by any template.
type renderData struct {
	InitClass string              // e.g. "ComposerAutoloaderInitabc..."
	Hash      string              // 32-hex chars
	PSR4      map[string][]string // prefix -> []relativeDir (trailing slash)
	// SortedPSR4 is supplied alongside PSR4 so templates iterate in
	// deterministic order without resorting on each render.
	SortedPSR4 []string
	// PSR4ByFirstChar groups SortedPSR4 by first character for use in
	// $prefixLengthsPsr4 in autoload_static.php. Ordered by first char.
	PSR4ByFirstChar []firstCharGroup
	Files           []FileEntry       // ordered, deduped, ready to emit
	Classmap        map[string]string // qualified-name -> project-relative path
	SortedClasses   []string          // sorted keys of Classmap, supplied for determinism
	Installed       InstalledData
}

// fileKey is the deterministic hash key Composer uses in autoload_files
// arrays: md5(packageName . ":" . relativePath). For the root manifest
// (PackageName == "") Composer hashes md5(absolute baseDir + path); we
// stand in with md5("__root__:" + path) so two checkouts of the same
// project on different machines still produce the same key. The bootstrap
// only ever uses the keys for `isset($GLOBALS[...][...])` dedup so any
// stable string works.
func fileKey(f FileEntry) string {
	owner := f.PackageName
	if owner == "" {
		owner = "__root__"
	}
	sum := md5.Sum([]byte(owner + ":" + f.Path))
	return hex.EncodeToString(sum[:])
}

// firstCharGroup is one bucket in $prefixLengthsPsr4: all PSR-4 prefixes
// that share the same first character, in sorted order.
type firstCharGroup struct {
	Char     string   // single character, e.g. "A"
	Prefixes []string // sorted prefixes starting with Char
}

// autoloadPHPTpl is the canonical entrypoint that user code includes via
// `require 'vendor/autoload.php'`. We track Composer's exact bytes here.
const autoloadPHPTpl = `<?php

// autoload.php @generated by gomposer

require_once __DIR__ . '/composer/autoload_real.php';

return {{.InitClass}}::getLoader();
`

// autoloadRealTpl defines the init class. It now includes the
// composerRequire<HASH> helper and the $includeFiles loop for the `files`
// autoloader, matching Composer's post-2.0 bootstrap shape.
const autoloadRealTpl = `<?php

// autoload_real.php @generated by gomposer

class {{.InitClass}}
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        spl_autoload_register(array('{{.InitClass}}', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('{{.InitClass}}', 'loadClassLoader'));

        $useStaticLoader = PHP_VERSION_ID >= 50600 && !defined('HHVM_VERSION');
        if ($useStaticLoader) {
            require __DIR__ . '/autoload_static.php';
            call_user_func(\Composer\Autoload\ComposerStaticInit{{.Hash}}::getInitializer($loader));
        } else {
            $map = require __DIR__ . '/autoload_namespaces.php';
            foreach ($map as $namespace => $path) {
                $loader->set($namespace, $path);
            }

            $map = require __DIR__ . '/autoload_psr4.php';
            foreach ($map as $namespace => $path) {
                $loader->setPsr4($namespace, $path);
            }

            $classMap = require __DIR__ . '/autoload_classmap.php';
            if ($classMap) {
                $loader->addClassMap($classMap);
            }
        }

        $loader->register(true);

        $includeFiles = $useStaticLoader ? \Composer\Autoload\ComposerStaticInit{{.Hash}}::$files : require __DIR__ . '/autoload_files.php';
        foreach ($includeFiles as $fileIdentifier => $file) {
            composerRequire{{.Hash}}($fileIdentifier, $file);
        }

        return $loader;
    }
}

function composerRequire{{.Hash}}($fileIdentifier, $file)
{
    if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
        $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;

        require $file;
    }
}
`

// autoloadPSR4Tpl writes the prefix -> [absolute-path, ...] map.
// We use $vendorDir/$baseDir constants to mirror Composer's exact shape.
const autoloadPSR4Tpl = `<?php

// autoload_psr4.php @generated by gomposer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
{{- range $prefix := .SortedPSR4}}
    {{phpString $prefix}} => array({{range $i, $dir := index $.PSR4 $prefix}}{{if $i}}, {{end}}{{phpDir $dir}}{{end}}),
{{- end}}
);
`

// autoloadNamespacesTpl is always empty in Stage 1 (PSR-0 deferred).
const autoloadNamespacesTpl = `<?php

// autoload_namespaces.php @generated by gomposer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
);
`

const autoloadClassmapTpl = `<?php

// autoload_classmap.php @generated by gomposer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
{{- range $name := .SortedClasses}}
    {{phpString $name}} => {{phpDir (index $.Classmap $name)}},
{{- end}}
);
`

const autoloadFilesTpl = `<?php

// autoload_files.php @generated by gomposer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
{{- range $f := .Files}}
    {{phpString (fileKey $f)}} => {{phpDir $f.Path}},
{{- end}}
);
`

// autoloadStaticTpl mirrors Composer's --optimize-autoloader output. It
// includes $files (for the `files` autoloader) and $classMap (for classmap).
const autoloadStaticTpl = `<?php

// autoload_static.php @generated by gomposer

namespace Composer\Autoload;

class ComposerStaticInit{{.Hash}}
{
    public static $files = array(
{{- range $f := .Files}}
        {{phpString (fileKey $f)}} => {{phpStaticDir $f.Path}},
{{- end}}
    );

    public static $prefixLengthsPsr4 = array(
{{- range .PSR4ByFirstChar}}
        {{phpString .Char}} => array({{range $i, $p := .Prefixes}}{{if $i}}, {{end}}{{phpString $p}} => {{len $p}}{{end}}),
{{- end}}
    );

    public static $prefixDirsPsr4 = array(
{{- range $prefix := .SortedPSR4}}
        {{phpString $prefix}} => array({{range $i, $dir := index $.PSR4 $prefix}}{{if $i}}, {{end}}{{phpStaticDir $dir}}{{end}}),
{{- end}}
    );

    public static $classMap = array(
{{- range $name := .SortedClasses}}
        {{phpString $name}} => {{phpStaticDir (index $.Classmap $name)}},
{{- end}}
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit{{.Hash}}::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit{{.Hash}}::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit{{.Hash}}::$classMap;
        }, null, ClassLoader::class);
    }
}
`

const installedTpl = `<?php return array(
    'root' => array(
        'name' => {{phpString .Installed.Root.Name}},
        'pretty_version' => {{phpString .Installed.Root.PrettyVersion}},
        'version' => {{phpString .Installed.Root.Version}},
        'reference' => {{phpNullable .Installed.Root.Reference}},
        'type' => {{phpString .Installed.Root.Type}},
        'install_path' => __DIR__ . '/../../',
        'aliases' => array({{range $i, $alias := .Installed.Root.Aliases}}{{if $i}}, {{end}}{{phpString $alias}}{{end}}),
        'dev' => {{phpBool .Installed.Root.Dev}},
    ),
    'versions' => array(
        {{phpString .Installed.Root.Name}} => array(
            'pretty_version' => {{phpString .Installed.Root.PrettyVersion}},
            'version' => {{phpString .Installed.Root.Version}},
            'reference' => {{phpNullable .Installed.Root.Reference}},
            'type' => {{phpString .Installed.Root.Type}},
            'install_path' => __DIR__ . '/../../',
            'aliases' => array({{range $i, $alias := .Installed.Root.Aliases}}{{if $i}}, {{end}}{{phpString $alias}}{{end}}),
            'dev_requirement' => false,
        ),{{range .Installed.Packages}}
        {{phpString .Name}} => array(
            'pretty_version' => {{phpString .PrettyVersion}},
            'version' => {{phpString .Version}},
            'reference' => {{phpNullable .Reference}},
            'type' => {{phpString .Type}},
            'install_path' => {{phpInstallPath .InstallPath}},
            'aliases' => array({{range $i, $alias := .Aliases}}{{if $i}}, {{end}}{{phpString $alias}}{{end}}),
            'dev_requirement' => {{phpBool .DevRequirement}},
        ),{{end}}
    ),
);
`

const installedVersionsTpl = `<?php

// InstalledVersions.php @generated by gomposer

namespace Composer;

class InstalledVersions
{
    private static $installed;
    private static $canGetVendors;

    public static function getInstalledPackages()
    {
        $packages = array();
        foreach (self::getInstalledDataSets() as $installed) {
            $packages[] = array_keys($installed['versions']);
        }
        return array_values(array_unique(array_merge(...$packages)));
    }

    public static function getInstalledPackagesByType($type)
    {
        $packages = array();
        foreach (self::getInstalledDataSets() as $installed) {
            foreach ($installed['versions'] as $name => $package) {
                if (isset($package['type']) && $package['type'] === $type) {
                    $packages[] = $name;
                }
            }
        }
        return array_values(array_unique($packages));
    }

    public static function isInstalled($packageName, $includeDevRequirements = true)
    {
        foreach (self::getInstalledDataSets() as $installed) {
            if (isset($installed['versions'][$packageName]) && ($includeDevRequirements || empty($installed['versions'][$packageName]['dev_requirement']))) {
                return true;
            }
        }
        return false;
    }

    public static function satisfies(\Composer\Semver\VersionParser $parser, $packageName, $constraint)
    {
        $constraint = $parser->parseConstraints($constraint);
        $provided = $parser->parseConstraints(self::getVersionRanges($packageName));
        return $provided->matches($constraint);
    }

    public static function getVersionRanges($packageName)
    {
        foreach (self::getInstalledDataSets() as $installed) {
            if (!isset($installed['versions'][$packageName])) {
                continue;
            }
            $ranges = array();
            if (isset($installed['versions'][$packageName]['version'])) {
                $ranges[] = $installed['versions'][$packageName]['version'];
            }
            if (!empty($installed['versions'][$packageName]['aliases'])) {
                $ranges = array_merge($ranges, $installed['versions'][$packageName]['aliases']);
            }
            if (!empty($installed['versions'][$packageName]['replaced'])) {
                $ranges = array_merge($ranges, $installed['versions'][$packageName]['replaced']);
            }
            if (!empty($installed['versions'][$packageName]['provided'])) {
                $ranges = array_merge($ranges, $installed['versions'][$packageName]['provided']);
            }
            return implode(' || ', $ranges);
        }
        throw new \OutOfBoundsException('Package "' . $packageName . '" is not installed');
    }

    public static function getVersion($packageName)
    {
        return self::getPackageField($packageName, 'version');
    }

    public static function getPrettyVersion($packageName)
    {
        return self::getPackageField($packageName, 'pretty_version');
    }

    public static function getReference($packageName)
    {
        return self::getPackageField($packageName, 'reference');
    }

    public static function getInstallPath($packageName)
    {
        return self::getPackageField($packageName, 'install_path');
    }

    public static function getRootPackage()
    {
        return self::getRawData()['root'];
    }

    public static function getRawData()
    {
        return self::getInstalled();
    }

    public static function getAllRawData()
    {
        return self::getInstalledDataSets();
    }

    public static function reload($data)
    {
        self::$installed = $data;
    }

    private static function getPackageField($packageName, $field)
    {
        foreach (self::getInstalledDataSets() as $installed) {
            if (isset($installed['versions'][$packageName])) {
                return isset($installed['versions'][$packageName][$field]) ? $installed['versions'][$packageName][$field] : null;
            }
        }
        throw new \OutOfBoundsException('Package "' . $packageName . '" is not installed');
    }

    private static function getInstalledDataSets()
    {
        $installed = array(self::getInstalled());
        if (self::$canGetVendors) {
            foreach (\Composer\Autoload\ClassLoader::getRegisteredLoaders() as $vendorDir => $loader) {
                $installedFile = $vendorDir . '/composer/installed.php';
                if (__DIR__ . '/installed.php' !== $installedFile && is_file($installedFile)) {
                    $installed[] = require $installedFile;
                }
            }
        }
        return $installed;
    }

    private static function getInstalled()
    {
        if (null === self::$installed) {
            self::$installed = require __DIR__ . '/installed.php';
        }
        if (null === self::$canGetVendors) {
            self::$canGetVendors = method_exists('Composer\\Autoload\\ClassLoader', 'getRegisteredLoaders');
        }
        return self::$installed;
    }
}
`

// renderAll renders every template to a map keyed by relative output path.
func renderAll(d renderData) (map[string][]byte, error) {
	files := []struct {
		path, tpl string
	}{
		{"vendor/autoload.php", autoloadPHPTpl},
		{"vendor/composer/autoload_real.php", autoloadRealTpl},
		{"vendor/composer/autoload_psr4.php", autoloadPSR4Tpl},
		{"vendor/composer/autoload_namespaces.php", autoloadNamespacesTpl},
		{"vendor/composer/autoload_classmap.php", autoloadClassmapTpl},
		{"vendor/composer/autoload_files.php", autoloadFilesTpl},
		{"vendor/composer/autoload_static.php", autoloadStaticTpl},
		{"vendor/composer/installed.php", installedTpl},
		{"vendor/composer/InstalledVersions.php", installedVersionsTpl},
	}
	out := make(map[string][]byte, len(files))
	for _, f := range files {
		b, err := renderOne(f.tpl, d)
		if err != nil {
			return nil, fmt.Errorf("autoload: render %s: %w", f.path, err)
		}
		out[f.path] = b
	}
	return out, nil
}

func renderOne(tpl string, d renderData) ([]byte, error) {
	t := template.New("").Funcs(template.FuncMap{
		"phpString":   phpString,
		"phpNullable": phpNullable,
		"phpBool": func(v bool) string {
			if v {
				return "true"
			}
			return "false"
		},
		"phpInstallPath": phpInstallPath,
		"phpDir":         phpDir,
		"phpStaticDir":   phpStaticDir,
		"firstChar":      firstChar,
		"fileKey":        fileKey,
		"len":            func(s string) int { return len(s) },
	})
	t, err := t.Parse(tpl)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, d); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// phpString emits a single-quoted PHP string with backslashes and single
// quotes escaped. PHP single-quoted strings only need those two escapes,
// which matches what Composer emits. Newlines in keys would be invalid
// PSR-4 namespaces so we don't try to escape them.
func phpString(s string) string {
	r := make([]byte, 0, len(s)+2)
	r = append(r, '\'')
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch c {
		case '\\':
			r = append(r, '\\', '\\')
		case '\'':
			r = append(r, '\\', '\'')
		default:
			r = append(r, c)
		}
	}
	r = append(r, '\'')
	return string(r)
}

func phpNullable(s string) string {
	if s == "" {
		return "null"
	}
	return phpString(s)
}

func phpInstallPath(rel string) string {
	rel = trimTrailingSlash(rel)
	const vendorPrefix = "vendor/"
	if strings.HasPrefix(rel, vendorPrefix) {
		return "__DIR__ . '/..' . " + phpString("/"+rel[len(vendorPrefix):])
	}
	return "__DIR__ . '/../..' . " + phpString("/"+rel)
}

// phpStaticDir emits a __DIR__-relative expression for use inside
// class static property initializers in autoload_static.php. PHP static
// property initializers must be constant expressions, so we use string
// concatenation with the __DIR__ magic constant (allowed since PHP 5.6).
//
// __DIR__ in vendor/composer/autoload_static.php resolves to vendor/composer.
// Therefore:
//   - vendor/acme/foo/src → __DIR__ . '/..' . '/acme/foo/src'
//   - src (project root)  → __DIR__ . '/../..' . '/src'
func phpStaticDir(rel string) string {
	rel = trimTrailingSlash(rel)
	const vendorPrefix = "vendor/"
	if len(rel) >= len(vendorPrefix) && rel[:len(vendorPrefix)] == vendorPrefix {
		return "__DIR__ . '/..' . " + phpString("/"+rel[len(vendorPrefix):])
	}
	if rel == "" {
		return "__DIR__ . '/../..'"
	}
	return "__DIR__ . '/../..' . " + phpString("/"+rel)
}

// phpDir emits a directory expression like "$vendorDir . '/acme/foo/src'"
// when the path lives under vendor/, or "$baseDir . '/src'" otherwise.
// Trailing slashes are stripped because Composer never emits them inside
// the array (the runtime adds them).
func phpDir(rel string) string {
	rel = trimTrailingSlash(rel)
	const vendorPrefix = "vendor/"
	if len(rel) >= len(vendorPrefix) && rel[:len(vendorPrefix)] == vendorPrefix {
		return "$vendorDir . " + phpString("/"+rel[len(vendorPrefix):])
	}
	if rel == "" {
		return "$baseDir . " + phpString("/")
	}
	return "$baseDir . " + phpString("/"+rel)
}

func trimTrailingSlash(s string) string {
	for len(s) > 0 && s[len(s)-1] == '/' {
		s = s[:len(s)-1]
	}
	return s
}

// firstChar returns the first character of s as a length-1 string.
// Used by autoload_static.php's prefixLengthsPsr4 buckets.
func firstChar(s string) string {
	if s == "" {
		return ""
	}
	return s[:1]
}

// buildFirstCharGroups groups sortedPrefixes by first character into
// ordered buckets, matching Composer's $prefixLengthsPsr4 shape.
// Input must already be sorted lexicographically.
func buildFirstCharGroups(sortedPrefixes []string) []firstCharGroup {
	var groups []firstCharGroup
	for _, p := range sortedPrefixes {
		if p == "" {
			continue
		}
		ch := p[:1]
		if len(groups) > 0 && groups[len(groups)-1].Char == ch {
			groups[len(groups)-1].Prefixes = append(groups[len(groups)-1].Prefixes, p)
		} else {
			groups = append(groups, firstCharGroup{Char: ch, Prefixes: []string{p}})
		}
	}
	return groups
}
