package autoload

import (
	"bytes"
	"fmt"
	"text/template"
)

// renderData carries every value referenced by any template.
type renderData struct {
	InitClass string              // e.g. "ComposerAutoloaderInitabc..."
	Hash      string              // 32-hex chars
	PSR4      map[string][]string // prefix -> []relativeDir (trailing slash)
	// SortedPSR4 is supplied alongside PSR4 so templates iterate in
	// deterministic order without resorting on each render.
	SortedPSR4 []string
	// PSR4ByFirstChar groups SortedPSR4 by first character for use in
	// $prefixLengthsPsr4 in autoload_static.php. Ordered by first char.
	PSR4ByFirstChar []firstCharGroup
}

// firstCharGroup is one bucket in $prefixLengthsPsr4: all PSR-4 prefixes
// that share the same first character, in sorted order.
type firstCharGroup struct {
	Char     string   // single character, e.g. "A"
	Prefixes []string // sorted prefixes starting with Char
}

// autoloadPHPTpl is the canonical entrypoint that user code includes via
// `require 'vendor/autoload.php'`. We track Composer's exact bytes here.
const autoloadPHPTpl = `<?php

// autoload.php @generated by composer-go

require_once __DIR__ . '/composer/autoload_real.php';

return {{.InitClass}}::getLoader();
`

// autoloadRealTpl defines the init class. Composer's real version handles
// optimize-autoloader, apc, suffix, etc.; for Stage 1 we only need the
// non-optimized path. Stage 2 will extend this template (or fork it).
const autoloadRealTpl = `<?php

// autoload_real.php @generated by composer-go

class {{.InitClass}}
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        spl_autoload_register(array('{{.InitClass}}', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('{{.InitClass}}', 'loadClassLoader'));

        $useStaticLoader = PHP_VERSION_ID >= 50600 && !defined('HHVM_VERSION');
        if ($useStaticLoader) {
            require __DIR__ . '/autoload_static.php';
            call_user_func(\Composer\Autoload\ComposerStaticInit{{.Hash}}::getInitializer($loader));
        } else {
            $map = require __DIR__ . '/autoload_namespaces.php';
            foreach ($map as $namespace => $path) {
                $loader->set($namespace, $path);
            }

            $map = require __DIR__ . '/autoload_psr4.php';
            foreach ($map as $namespace => $path) {
                $loader->setPsr4($namespace, $path);
            }

            $classMap = require __DIR__ . '/autoload_classmap.php';
            if ($classMap) {
                $loader->addClassMap($classMap);
            }
        }

        $loader->register(true);

        return $loader;
    }
}
`

// autoloadPSR4Tpl writes the prefix -> [absolute-path, ...] map.
// We use $vendorDir/$baseDir constants to mirror Composer's exact shape.
const autoloadPSR4Tpl = `<?php

// autoload_psr4.php @generated by composer-go

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
{{- range $prefix := .SortedPSR4}}
    {{phpString $prefix}} => array({{range $i, $dir := index $.PSR4 $prefix}}{{if $i}}, {{end}}{{phpDir $dir}}{{end}}),
{{- end}}
);
`

// autoloadNamespacesTpl is always empty in Stage 1 (PSR-0 deferred).
const autoloadNamespacesTpl = `<?php

// autoload_namespaces.php @generated by composer-go

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
);
`

// autoloadClassmapTpl is always empty in Stage 1.
const autoloadClassmapTpl = `<?php

// autoload_classmap.php @generated by composer-go

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
);
`

// autoloadFilesTpl is always empty in Stage 1.
const autoloadFilesTpl = `<?php

// autoload_files.php @generated by composer-go

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
);
`

// autoloadStaticTpl mirrors Composer's --optimize-autoloader output for
// the PSR-4 portion only. It is required because autoload_real.php prefers
// it on PHP >= 5.6. In Stage 2 we expand this with classmap and files.
//
// $prefixLengthsPsr4 groups prefixes by their first character, matching
// Composer's exact output format (one array key per unique first char).
// $prefixDirsPsr4 uses __DIR__-relative expressions so the bundle is
// portable across machines (matches Composer's own output style).
const autoloadStaticTpl = `<?php

// autoload_static.php @generated by composer-go

namespace Composer\Autoload;

class ComposerStaticInit{{.Hash}}
{
    public static $prefixLengthsPsr4 = array(
{{- range .PSR4ByFirstChar}}
        {{phpString .Char}} => array({{range $i, $p := .Prefixes}}{{if $i}}, {{end}}{{phpString $p}} => {{len $p}}{{end}}),
{{- end}}
    );

    public static $prefixDirsPsr4 = array(
{{- range $prefix := .SortedPSR4}}
        {{phpString $prefix}} => array({{range $i, $dir := index $.PSR4 $prefix}}{{if $i}}, {{end}}{{phpStaticDir $dir}}{{end}}),
{{- end}}
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit{{.Hash}}::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit{{.Hash}}::$prefixDirsPsr4;
        }, null, ClassLoader::class);
    }
}
`

// installedTpl is a minimal stub for Stage 1. Symfony/Laravel begin to read
// this in Stage 2; until then "no installed packages info available" is
// acceptable. The format mirrors Composer/InstalledVersions array shape.
const installedTpl = `<?php return array(
    'root' => array(
        'name' => 'composer-go/stage1-stub',
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'reference' => null,
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => false,
    ),
    'versions' => array(),
);
`

// installedVersionsTpl is the InstalledVersions class. Stage 1 ships a
// stub that returns empty data; Symfony 6+, Laravel 10+, and any package
// that calls Composer\InstalledVersions::*() will get null/empty answers
// rather than fatal errors. Stage 2 (Real-world coverage) replaces this
// with a faithful port. The TODO marker below is grep-friendly:
//
//	TODO(stage2): port full InstalledVersions implementation
const installedVersionsTpl = `<?php

// InstalledVersions.php @generated by composer-go (Stage 1 stub)
//
// This is a minimal stub. Stage 2 will replace it with the full
// InstalledVersions implementation. User code that calls into this class
// will receive empty/null answers rather than a fatal error.

namespace Composer;

class InstalledVersions
{
    private static $installed;

    public static function getInstallPath($packageName)
    {
        return null;
    }

    public static function getInstalledPackages()
    {
        return array();
    }

    public static function isInstalled($packageName, $includeDevRequirements = true)
    {
        return false;
    }

    public static function getVersion($packageName)
    {
        return null;
    }

    public static function getPrettyVersion($packageName)
    {
        return null;
    }

    public static function getRootPackage()
    {
        $installed = self::getInstalled();
        return $installed['root'];
    }

    public static function getAllRawData()
    {
        return array(self::getInstalled());
    }

    private static function getInstalled()
    {
        if (null === self::$installed) {
            self::$installed = require __DIR__ . '/installed.php';
        }
        return self::$installed;
    }
}
`

// renderAll renders every template to a map keyed by relative output path.
func renderAll(d renderData) (map[string][]byte, error) {
	files := []struct {
		path, tpl string
	}{
		{"vendor/autoload.php", autoloadPHPTpl},
		{"vendor/composer/autoload_real.php", autoloadRealTpl},
		{"vendor/composer/autoload_psr4.php", autoloadPSR4Tpl},
		{"vendor/composer/autoload_namespaces.php", autoloadNamespacesTpl},
		{"vendor/composer/autoload_classmap.php", autoloadClassmapTpl},
		{"vendor/composer/autoload_files.php", autoloadFilesTpl},
		{"vendor/composer/autoload_static.php", autoloadStaticTpl},
		{"vendor/composer/installed.php", installedTpl},
		{"vendor/composer/InstalledVersions.php", installedVersionsTpl},
	}
	out := make(map[string][]byte, len(files))
	for _, f := range files {
		b, err := renderOne(f.tpl, d)
		if err != nil {
			return nil, fmt.Errorf("autoload: render %s: %w", f.path, err)
		}
		out[f.path] = b
	}
	return out, nil
}

func renderOne(tpl string, d renderData) ([]byte, error) {
	t := template.New("").Funcs(template.FuncMap{
		"phpString":    phpString,
		"phpDir":       phpDir,
		"phpStaticDir": phpStaticDir,
		"firstChar":    firstChar,
		"len":          func(s string) int { return len(s) },
	})
	t, err := t.Parse(tpl)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, d); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// phpString emits a single-quoted PHP string with backslashes and single
// quotes escaped. PHP single-quoted strings only need those two escapes,
// which matches what Composer emits. Newlines in keys would be invalid
// PSR-4 namespaces so we don't try to escape them.
func phpString(s string) string {
	r := make([]byte, 0, len(s)+2)
	r = append(r, '\'')
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch c {
		case '\\':
			r = append(r, '\\', '\\')
		case '\'':
			r = append(r, '\\', '\'')
		default:
			r = append(r, c)
		}
	}
	r = append(r, '\'')
	return string(r)
}

// phpStaticDir emits a __DIR__-relative expression for use inside
// class static property initializers in autoload_static.php. PHP static
// property initializers must be constant expressions, so we use string
// concatenation with the __DIR__ magic constant (allowed since PHP 5.6).
//
// __DIR__ in vendor/composer/autoload_static.php resolves to vendor/composer.
// Therefore:
//   - vendor/acme/foo/src → __DIR__ . '/..' . '/acme/foo/src'
//   - src (project root)  → __DIR__ . '/../..' . '/src'
func phpStaticDir(rel string) string {
	rel = trimTrailingSlash(rel)
	const vendorPrefix = "vendor/"
	if len(rel) >= len(vendorPrefix) && rel[:len(vendorPrefix)] == vendorPrefix {
		return "__DIR__ . '/..' . " + phpString("/"+rel[len(vendorPrefix):])
	}
	if rel == "" {
		return "__DIR__ . '/../..'"
	}
	return "__DIR__ . '/../..' . " + phpString("/"+rel)
}

// phpDir emits a directory expression like "$vendorDir . '/acme/foo/src'"
// when the path lives under vendor/, or "$baseDir . '/src'" otherwise.
// Trailing slashes are stripped because Composer never emits them inside
// the array (the runtime adds them).
func phpDir(rel string) string {
	rel = trimTrailingSlash(rel)
	const vendorPrefix = "vendor/"
	if len(rel) >= len(vendorPrefix) && rel[:len(vendorPrefix)] == vendorPrefix {
		return "$vendorDir . " + phpString("/"+rel[len(vendorPrefix):])
	}
	if rel == "" {
		return "$baseDir . " + phpString("/")
	}
	return "$baseDir . " + phpString("/"+rel)
}

func trimTrailingSlash(s string) string {
	for len(s) > 0 && s[len(s)-1] == '/' {
		s = s[:len(s)-1]
	}
	return s
}

// firstChar returns the first character of s as a length-1 string.
// Used by autoload_static.php's prefixLengthsPsr4 buckets.
func firstChar(s string) string {
	if s == "" {
		return ""
	}
	return s[:1]
}

// buildFirstCharGroups groups sortedPrefixes by first character into
// ordered buckets, matching Composer's $prefixLengthsPsr4 shape.
// Input must already be sorted lexicographically.
func buildFirstCharGroups(sortedPrefixes []string) []firstCharGroup {
	var groups []firstCharGroup
	for _, p := range sortedPrefixes {
		if p == "" {
			continue
		}
		ch := p[:1]
		if len(groups) > 0 && groups[len(groups)-1].Char == ch {
			groups[len(groups)-1].Prefixes = append(groups[len(groups)-1].Prefixes, p)
		} else {
			groups = append(groups, firstCharGroup{Char: ch, Prefixes: []string{p}})
		}
	}
	return groups
}
