<?php

// autoload_static.php @generated by composer-go

namespace Composer\Autoload;

class ComposerStaticInit3b346b2bf25853783abd920b5c5bf21c
{
    public static $prefixLengthsPsr4 = array(
        'A' => array('Acme\\Bar\\' => 9, 'Acme\\Foo\\' => 9, 'App\\' => 4),
    );

    public static $prefixDirsPsr4 = array(
        'Acme\\Bar\\' => array(__DIR__ . '/..' . '/acme/bar/src'),
        'Acme\\Foo\\' => array(__DIR__ . '/..' . '/acme/foo/src'),
        'App\\' => array(__DIR__ . '/../..' . '/src'),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit3b346b2bf25853783abd920b5c5bf21c::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit3b346b2bf25853783abd920b5c5bf21c::$prefixDirsPsr4;
        }, null, ClassLoader::class);
    }
}
