<?php

// autoload_psr4.php @generated by composer-go

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Acme\\Bar\\' => array($vendorDir . '/acme/bar/src'),
    'Acme\\Foo\\' => array($vendorDir . '/acme/foo/src'),
    'App\\' => array($baseDir . '/src'),
    'Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
);
