<?php

// autoload_static.php @generated by composer-go

namespace Composer\Autoload;

class ComposerStaticInitcd4abb5c1a428281a6432bd0afc8d785
{
    public static $files = array(
        '0504388a4555084b5673da0172ddce99' => __DIR__ . '/..' . '/symfony/polyfill-mbstring/bootstrap.php',
    );

    public static $prefixLengthsPsr4 = array(
        'A' => array('Acme\\Bar\\' => 9, 'Acme\\Foo\\' => 9, 'App\\' => 4),
        'S' => array('Symfony\\Polyfill\\Mbstring\\' => 26),
    );

    public static $prefixDirsPsr4 = array(
        'Acme\\Bar\\' => array(__DIR__ . '/..' . '/acme/bar/src'),
        'Acme\\Foo\\' => array(__DIR__ . '/..' . '/acme/foo/src'),
        'App\\' => array(__DIR__ . '/../..' . '/src'),
        'Symfony\\Polyfill\\Mbstring\\' => array(__DIR__ . '/..' . '/symfony/polyfill-mbstring'),
    );

    public static $classMap = array(
        'Acme\\Legacy\\Loud' => __DIR__ . '/..' . '/acme/legacy/src/Old.php',
        'Acme\\Legacy\\Old' => __DIR__ . '/..' . '/acme/legacy/src/Old.php',
        'Acme\\Legacy\\Speaker' => __DIR__ . '/..' . '/acme/legacy/src/Old.php',
        'Acme\\Legacy\\Sub\\Color' => __DIR__ . '/..' . '/acme/legacy/src/sub/Sub.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitcd4abb5c1a428281a6432bd0afc8d785::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitcd4abb5c1a428281a6432bd0afc8d785::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitcd4abb5c1a428281a6432bd0afc8d785::$classMap;
        }, null, ClassLoader::class);
    }
}
