<?php

// InstalledVersions.php @generated by gomposer

namespace Composer;

class InstalledVersions
{
    private static $installed;
    private static $canGetVendors;

    public static function getInstalledPackages()
    {
        $packages = array();
        foreach (self::getInstalledDataSets() as $installed) {
            $packages[] = array_keys($installed['versions']);
        }
        return array_values(array_unique(array_merge(...$packages)));
    }

    public static function getInstalledPackagesByType($type)
    {
        $packages = array();
        foreach (self::getInstalledDataSets() as $installed) {
            foreach ($installed['versions'] as $name => $package) {
                if (isset($package['type']) && $package['type'] === $type) {
                    $packages[] = $name;
                }
            }
        }
        return array_values(array_unique($packages));
    }

    public static function isInstalled($packageName, $includeDevRequirements = true)
    {
        foreach (self::getInstalledDataSets() as $installed) {
            if (isset($installed['versions'][$packageName]) && ($includeDevRequirements || empty($installed['versions'][$packageName]['dev_requirement']))) {
                return true;
            }
        }
        return false;
    }

    public static function satisfies(\Composer\Semver\VersionParser $parser, $packageName, $constraint)
    {
        $constraint = $parser->parseConstraints($constraint);
        $provided = $parser->parseConstraints(self::getVersionRanges($packageName));
        return $provided->matches($constraint);
    }

    public static function getVersionRanges($packageName)
    {
        foreach (self::getInstalledDataSets() as $installed) {
            if (!isset($installed['versions'][$packageName])) {
                continue;
            }
            $ranges = array();
            if (isset($installed['versions'][$packageName]['version'])) {
                $ranges[] = $installed['versions'][$packageName]['version'];
            }
            if (!empty($installed['versions'][$packageName]['aliases'])) {
                $ranges = array_merge($ranges, $installed['versions'][$packageName]['aliases']);
            }
            if (!empty($installed['versions'][$packageName]['replaced'])) {
                $ranges = array_merge($ranges, $installed['versions'][$packageName]['replaced']);
            }
            if (!empty($installed['versions'][$packageName]['provided'])) {
                $ranges = array_merge($ranges, $installed['versions'][$packageName]['provided']);
            }
            return implode(' || ', $ranges);
        }
        throw new \OutOfBoundsException('Package "' . $packageName . '" is not installed');
    }

    public static function getVersion($packageName)
    {
        return self::getPackageField($packageName, 'version');
    }

    public static function getPrettyVersion($packageName)
    {
        return self::getPackageField($packageName, 'pretty_version');
    }

    public static function getReference($packageName)
    {
        return self::getPackageField($packageName, 'reference');
    }

    public static function getInstallPath($packageName)
    {
        return self::getPackageField($packageName, 'install_path');
    }

    public static function getRootPackage()
    {
        return self::getRawData()['root'];
    }

    public static function getRawData()
    {
        return self::getInstalled();
    }

    public static function getAllRawData()
    {
        return self::getInstalledDataSets();
    }

    public static function reload($data)
    {
        self::$installed = $data;
    }

    private static function getPackageField($packageName, $field)
    {
        foreach (self::getInstalledDataSets() as $installed) {
            if (isset($installed['versions'][$packageName])) {
                return isset($installed['versions'][$packageName][$field]) ? $installed['versions'][$packageName][$field] : null;
            }
        }
        throw new \OutOfBoundsException('Package "' . $packageName . '" is not installed');
    }

    private static function getInstalledDataSets()
    {
        $installed = array(self::getInstalled());
        if (self::$canGetVendors) {
            foreach (\Composer\Autoload\ClassLoader::getRegisteredLoaders() as $vendorDir => $loader) {
                $installedFile = $vendorDir . '/composer/installed.php';
                if (__DIR__ . '/installed.php' !== $installedFile && is_file($installedFile)) {
                    $installed[] = require $installedFile;
                }
            }
        }
        return $installed;
    }

    private static function getInstalled()
    {
        if (null === self::$installed) {
            self::$installed = require __DIR__ . '/installed.php';
        }
        if (null === self::$canGetVendors) {
            self::$canGetVendors = method_exists('Composer\\Autoload\\ClassLoader', 'getRegisteredLoaders');
        }
        return self::$installed;
    }
}
