<?php

// InstalledVersions.php @generated by composer-go (Stage 1 stub)
//
// This is a minimal stub. Stage 2 will replace it with the full
// InstalledVersions implementation. User code that calls into this class
// will receive empty/null answers rather than a fatal error.

namespace Composer;

class InstalledVersions
{
    private static $installed;

    public static function getInstallPath($packageName)
    {
        return null;
    }

    public static function getInstalledPackages()
    {
        return array();
    }

    public static function isInstalled($packageName, $includeDevRequirements = true)
    {
        return false;
    }

    public static function getVersion($packageName)
    {
        return null;
    }

    public static function getPrettyVersion($packageName)
    {
        return null;
    }

    public static function getRootPackage()
    {
        $installed = self::getInstalled();
        return $installed['root'];
    }

    public static function getAllRawData()
    {
        return array(self::getInstalled());
    }

    private static function getInstalled()
    {
        if (null === self::$installed) {
            self::$installed = require __DIR__ . '/installed.php';
        }
        return self::$installed;
    }
}
